Db updates amy
Amelia-exe/RageBot-v3 pull request #39
Opened 2020-09-08 09:35 UTC by Amelia-exe

2020-09-08 09:53 UTC, Dan6erbond commented on cogs/log.py
> +                    before.channel) or before.channel
This seems to be a typo where you'd want to use `before.channel.guild` or the shorthand `before.guild`.

2020-09-08 09:54 UTC, Dan6erbond commented on cogs/moderation.py
> +            guild.config.mute_role = muterole.id
This needs to be extended to ensure that a `Role` in the DB exists as well:
```py
role = repo.get_model(Role, Role.id==muterole.id, id=muterole.id)
guild.config.mute_role = role
```

2020-09-08 09:57 UTC, Dan6erbond commented on cogs/moderation.py
>              muterole = repo.get(Role, and_(
This bit is outdated from when roles still had toggles for their features, now instead you should use:
```suggestion
            muterole = guild.config.mute_role
```

2020-09-08 10:07 UTC, Dan6erbond requested changes
Lots of changes, great job! Some small errors, a couple of typos and usages of the old models and functions that need to be changed.

The new `DEFAULT_WELCOME_CHANNEL` as you added it won't work because the `member` does not exist when you're loading the file, and additionally you're storing a string instead of an int. At best what you can do is `guild.config.welcome_channel = member.guild.system_channel` every time you get the guild with `repo.get_guild()`, preferably adding it to the function's arguments and doing it within to avoid code duplication.

Something like this:
```py
def get_guild(self, guild_id, system_channel):
  # query logic...

  # initializer...

  if not guild.config.welcome_channel:
    guild.config.welcome_channel = system_channel

  self.pending_transactions = True
```

This will set the `welcome_channel` in your guild's config to the system channel you feed whenever it isn't set to anything else (which should only happen when creating new guilds), but this also means refactoring your use of the function to pass on `system_channel`.

2020-09-08 10:07 UTC, Dan6erbond commented on cogs/moderation.py
>              muterole = repo.get(Role, and_(
This bit is outdated from when roles still had toggles for their features, now instead you should use:
```py
muterole = guild.config.mute_role
```

2020-09-08 10:07 UTC, Dan6erbond commented on cogs/moderation.py
> +            guild.config.mute_role = muterole.id
This needs to be extended to ensure that a `Role` in the DB exists as well:
```py
role = repo.get_model(Role, Role.id==muterole.id, id=muterole.id)
guild.config.mute_role = role
```

2020-09-08 10:07 UTC, Dan6erbond commented on cogs/log.py
> +                    before.channel) or before.channel
This seems to be a typo where you'd want to use `before.channel.guild` or the shorthand `before.guild`.

2020-09-08 10:07 UTC, Dan6erbond commented on cogs/verify.py
>              guild = repo.get_guild(ctx.guild.id)
You can use the previous role logic here to ensure that the role is added to the DB by the repo if it doesn't exist:
```py
initial_role = repo.get_model(Role, Role.id==initialrole.id, id=initialrole.id)
guild.config.intial_role = initial_role
verified_role = repo.get_model(Role, Role.id==verifiedrole.id, id=verifiedrole.id)
guild.config.verified_role = verified_role 
```

2020-09-08 10:07 UTC, Dan6erbond commented on database/models/guild_config.py
> +DEFAULT_WELCOME_CHANNEL = "{member.guild.system_channel}"
This won't work because at the time of loading the file your `member` doesn't exist. There's also the *small* issue that you're saving a string and we need an int. 😉

2020-09-08 12:49 UTC, Amelia-exe commented on cogs/onmember.py
> +            if guild:
removed `if guild:` as it was not necessary.

2020-09-08 22:41 UTC, Amelia-exe commented on cogs/log.py
> +                    before.channel) or before.channel
yes. the bane of my day today 🙄 
Issue is now fixicated 👍🏻

2020-09-09 21:01 UTC, Amelia-exe commented on cogs/verify.py
>              guild = repo.get_guild(ctx.guild.id)
Made the change :'D
and added the aliases to the command.

2020-09-09 21:06 UTC, Amelia-exe commented on cogs/moderation.py
> +            guild.config.mute_role = muterole.id
Added the change

2020-09-09 21:13 UTC, Amelia-exe commented on cogs/moderation.py
>              muterole = repo.get(Role, and_(
updated ;D

2020-09-09 21:30 UTC, merged